"use client"

import React, { useState } from "react"
import { useServerInsertedHTML } from "next/navigation"
import { ServerStyleSheet, StyleSheetManager } from "styled-components"

/**
 * The purpose of `StyledComponentsRegistr` is to generate and insert the styles from
 * styled components during server-side rendering into the <head> HTML tag in the root layout.
 */

const StyledComponentsRegistry = ({
    children,
}: {
    children: React.ReactNode
}) => {
    // variable lazily created once and will persist across re-renders
    const [styledComponentsStyleSheet] = useState(() => new ServerStyleSheet())

    useServerInsertedHTML(() => {
        // collects the styled components generated by styled-components
        const styles = styledComponentsStyleSheet.getStyleElement()

        // Clearing the style tags generated by styled-components ensure a clean slate for each server-side
        // rendering request, preventing style accumulation, ensuring consistent rendering and reducing
        // overhead in the rendered HTML. It helps maintain a reliable and optimized server-side rendering
        // workflow in React applications.
        styledComponentsStyleSheet.instance.clearTag()
        return <>{styles}</>
    })

    if (typeof window !== "undefined") return <>{children}</>

    return (
        <StyleSheetManager sheet={styledComponentsStyleSheet.instance}>
            {children}
        </StyleSheetManager>
    )
}

export default StyledComponentsRegistry
